#!/bin/bash
cd ~/Dev/leetcode

EASY_DIR="src/easy"
MEDIUM_DIR="src/medium"
HARD_DIR="src/hard"

build_rows() {
  local dir="$1" diff="$2" badge="$3"
  find "$dir" -maxdepth 1 -name "*.java" 2>/dev/null | sort -t'[' -k2 -n | while IFS= read -r f; do
    name=$(basename "$f" .java)
    num=$(echo "$name" | grep -oP '\d+' | head -1)
    title=$(echo "$name" | sed 's/^\[[0-9]*\]//' | xargs)
    echo "| $badge | $num | [$title]($f) | Java |"
  done
}

EASY_COUNT=$(find "$EASY_DIR" -maxdepth 1 -name "*.java" 2>/dev/null | wc -l)
MEDIUM_COUNT=$(find "$MEDIUM_DIR" -maxdepth 1 -name "*.java" 2>/dev/null | wc -l)
HARD_COUNT=$(find "$HARD_DIR" -maxdepth 1 -name "*.java" 2>/dev/null | wc -l)
TOTAL=$((EASY_COUNT + MEDIUM_COUNT + HARD_COUNT))

EASY_ROWS=$(build_rows "$EASY_DIR" "Easy" "🟢")
MEDIUM_ROWS=$(build_rows "$MEDIUM_DIR" "Medium" "🟡")
HARD_ROWS=$(build_rows "$HARD_DIR" "Hard" "🔴")

cat > README.md << MDEOF
<div align="center">

# LeetCode Solutions

**Grinding LeetCode in Java — one problem at a time.**

[![Total](https://img.shields.io/badge/Total-${TOTAL}-4f46e5?style=for-the-badge)](.)
[![Easy](https://img.shields.io/badge/Easy-${EASY_COUNT}-22c55e?style=for-the-badge)](src/easy)
[![Medium](https://img.shields.io/badge/Medium-${MEDIUM_COUNT}-f59e0b?style=for-the-badge)](src/medium)
[![Hard](https://img.shields.io/badge/Hard-${HARD_COUNT}-ef4444?style=for-the-badge)](src/hard)

</div>

---

## Progress

\`\`\`
Easy    [$( printf '%.0s█' $(seq 1 $EASY_COUNT) )$( printf '%.0s░' $(seq 1 $((50 - EASY_COUNT > 0 ? 50 - EASY_COUNT : 0))) )] ${EASY_COUNT}
Medium  [$( printf '%.0s█' $(seq 1 $MEDIUM_COUNT) )$( printf '%.0s░' $(seq 1 $((50 - MEDIUM_COUNT > 0 ? 50 - MEDIUM_COUNT : 0))) )] ${MEDIUM_COUNT}
Hard    [$( printf '%.0s█' $(seq 1 $HARD_COUNT) )$( printf '%.0s░' $(seq 1 $((50 - HARD_COUNT > 0 ? 50 - HARD_COUNT : 0))) )] ${HARD_COUNT}
\`\`\`

---

## Solutions

| | # | Problem | Language |
|---|---|---|---|
${EASY_ROWS}
${MEDIUM_ROWS}
${HARD_ROWS}

---

<div align="center">
<sub>Last updated: $(date '+%Y-%m-%d %H:%M') · Auto-generated by <a href="update-readme.sh">update-readme.sh</a></sub>
</div>
MDEOF

echo "✅ README updated — Easy: $EASY_COUNT | Medium: $MEDIUM_COUNT | Hard: $HARD_COUNT | Total: $TOTAL"
