#!/bin/bash
cd ~/Dev/leetcode

EASY_DIR="src/easy"
MEDIUM_DIR="src/medium"
HARD_DIR="src/hard"

build_table() {
  local dir="$1"
  find "$dir" -maxdepth 1 -name "*.java" 2>/dev/null | sort -t'[' -k2 -n | while IFS= read -r f; do
    local name=$(basename "$f" .java)
    local num=$(echo "$name" | grep -oP '\d+' | head -1)
    local title=$(echo "$name" | sed 's/^\[[0-9]*\]//' | xargs)
    local url=$(echo "$f" | sed 's/\[/%5B/g; s/\]/%5D/g; s/ /%20/g')
    echo "| $num | [$title]($url) |"
  done
}

EASY_COUNT=$(find "$EASY_DIR" -maxdepth 1 -name "*.java" 2>/dev/null | wc -l)
MEDIUM_COUNT=$(find "$MEDIUM_DIR" -maxdepth 1 -name "*.java" 2>/dev/null | wc -l)
HARD_COUNT=$(find "$HARD_DIR" -maxdepth 1 -name "*.java" 2>/dev/null | wc -l)
TOTAL=$((EASY_COUNT + MEDIUM_COUNT + HARD_COUNT))

EASY_ROWS=$(build_table "$EASY_DIR")
MEDIUM_ROWS=$(build_table "$MEDIUM_DIR")
HARD_ROWS=$(build_table "$HARD_DIR")

python3 generate-progress.py "$EASY_COUNT" "$MEDIUM_COUNT" "$HARD_COUNT" > progress.svg

cat > README.md << MDEOF
<div align="center">

# LeetCode Solutions

**Grinding LeetCode in Java — one problem at a time.**

[![Total](https://img.shields.io/badge/Total-${TOTAL}-4f46e5?style=for-the-badge)](.)
[![Easy](https://img.shields.io/badge/Easy-${EASY_COUNT}-22c55e?style=for-the-badge)](src/easy)
[![Medium](https://img.shields.io/badge/Medium-${MEDIUM_COUNT}-f59e0b?style=for-the-badge)](src/medium)
[![Hard](https://img.shields.io/badge/Hard-${HARD_COUNT}-ef4444?style=for-the-badge)](src/hard)

</div>

---

## Progress

![Progress](progress.svg)

---

## Solutions

<details open>
<summary>🟢 Easy &nbsp;—&nbsp; <b>${EASY_COUNT} solved</b></summary>

| # | Problem |
|---|---|
${EASY_ROWS}

</details>

<details open>
<summary>🟡 Medium &nbsp;—&nbsp; <b>${MEDIUM_COUNT} solved</b></summary>

| # | Problem |
|---|---|
${MEDIUM_ROWS}

</details>

<details open>
<summary>🔴 Hard &nbsp;—&nbsp; <b>${HARD_COUNT} solved</b></summary>

| # | Problem |
|---|---|
${HARD_ROWS}

</details>

---

<div align="center">
<sub>Last updated: $(date '+%Y-%m-%d %H:%M') · Auto-generated by <a href="update-readme.sh">update-readme.sh</a></sub>
</div>
MDEOF

echo "✅ README updated — Easy: $EASY_COUNT | Medium: $MEDIUM_COUNT | Hard: $HARD_COUNT | Total: $TOTAL"
